### ISSUE TITLE
Certain tray icons in MATE are too small, but it's fixed in Arc

### ISSUE THREAD

**Issue by Anonymous1157** [i-mint/Cloudy#3]
Hi! I like using your theme, thanks for making it.

I've been having an issue where certain tray icons in MATE are too small when using Cloudy or other Arc-derived themes. I reported it in jnsh/arc-theme#104 and it turned out to be trivial to fix.

It would be cool if Cloudy could fix the same bug, essentially delete the line `-NaTrayApplet-icon-size: 16px;` from every variant's `gtk-3.0/gtk.css`. I already tested it on my machine and it works as intended.

**Comment by i-mint** [comment]
Thanks! @Anonymous1157, I will do it.

**Comment by Anonymous1157** [comment]
I updated to the latest commit and the theme works fine. Thank you!
