### ISSUE TITLE
Typo in gtk.css: "opacify" should be "opacity"

### ISSUE THREAD

**Issue by Anonymous1157** [i-mint/Cloudy#5]
I launched a GTK application from a terminal and noticed it was spewing errors:
```
(pluma:6250): Gtk-WARNING **: 07:52:06.557: Theme parsing error: gtk.css:4489:13: 'opacify' is not a valid property name
```

It looks like there was a typo that was accidentally copied into every variant's `gtk-3.0/gtk.css`: The word "opacify" was meant to say "opacity". Fixing this typo made the errors go away.

**Comment by i-mint** [comment]
Thanks! for report. I will fix it.
